import type { Card, Profile, Resource } from "./workspace";
export function shuffled<T>(items:readonly T[],random= Math.random):T[] {const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function matchingCards(cards:Card[],program:Profile["program"]):Card[] {
  const fronts=new Set<string>(),backs=new Set<string>();
  return shuffled(cards.filter(c=>{const front=c.front.trim().toLowerCase(),back=c.back.trim().toLowerCase();if(fronts.has(front)||backs.has(back))return false;fronts.add(front);backs.add(back);return true;})).slice(0,program==="pyp"?4:6);
}
const base={level:"All" as const,examYear:2027,createdAt:"2026-09-09T00:00:00.000Z",origin:"starter" as const,starred:false,sourceNotes:"Original practice examples, not official IB assessment items.",body:"",cards:[],questions:[]};
export const programmeStarters:Resource[]=[
  {...base,id:"starter-pyp-words",program:"pyp",kind:"flashcards",subject:"Language",title:"Word explorers",summary:"Match a word with its meaning, then use it in your own sentence.",cards:[
    {id:"p1",front:"Observe",back:"Look closely and notice details."},{id:"p2",front:"Compare",back:"Find things that are alike and different."},{id:"p3",front:"Predict",back:"Say what you think might happen next."},{id:"p4",front:"Habitat",back:"The place where a plant or animal lives."},{id:"p5",front:"Reflect",back:"Think about what you learned and what to try next."},{id:"p6",front:"Community",back:"People who share a place or do things together."}]},
  {...base,id:"starter-pyp-discover",program:"pyp",kind:"quiz",subject:"Science",title:"Little science discoveries",summary:"Make a prediction and explain what you notice.",questions:[
    {id:"ps1",question:"A plant has dry soil. What could help it grow?",options:["Give it the water it needs","Keep it in a closed dark box"],correctAnswer:0,explanation:"Plants need water and light to grow. Too much water can also be harmful, so check the soil."},
    {id:"ps2",question:"You want to compare two leaves. What could you look at?",options:["Only the name of the tree","Their shapes, sizes and colours"],correctAnswer:1,explanation:"Observing the same features helps you find similarities and differences."},
    {id:"ps3",question:"An ice cube is left in a warm room. What do you predict?",options:["It will melt into water","It will turn into a stone"],correctAnswer:0,explanation:"The ice takes in heat from its surroundings and changes from a solid to a liquid."},
    {id:"ps4",question:"What is a helpful thing to do when your prediction is different from your result?",options:["Hide the result","Look again and ask why"],correctAnswer:1,explanation:"Surprising results can help you learn. Describe what you observed and think of a new explanation."}]},
  {...base,id:"starter-myp-inquiry",program:"myp",kind:"flashcards",subject:"Sciences",title:"Inquiry connections",summary:"Connect investigation vocabulary with the thinking behind it.",cards:[
    {id:"mi1",front:"Independent variable",back:"The factor deliberately changed in an investigation."},{id:"mi2",front:"Dependent variable",back:"The outcome measured to see the effect of a change."},{id:"mi3",front:"Controlled variable",back:"A factor kept consistent to support a fair comparison."},{id:"mi4",front:"Evidence",back:"Observations or data used to support or challenge a claim."},{id:"mi5",front:"Limitation",back:"A feature of a method or evidence that restricts what can be concluded."},{id:"mi6",front:"Transfer",back:"Applying knowledge or a skill in a different situation."}]},
  {...base,id:"starter-myp-reasoning",program:"myp",kind:"quiz",subject:"Individuals and Societies",title:"Evidence detective",summary:"Choose the best next step when a claim needs checking.",questions:[
    {id:"mr1",question:"Two articles disagree about an event. What is the strongest first step?",options:["Choose the shorter article","Check each author's evidence and context","Choose the more popular article","Ignore both"],correctAnswer:1,explanation:"Checking sources, evidence and context helps explain why accounts differ."},
    {id:"mr2",question:"A survey only asked members of one sports team about exercise. What limits its conclusions?",options:["It contains numbers","Exercise cannot be studied","The sample may not represent the wider group","Surveys always prove causes"],correctAnswer:2,explanation:"Selection can affect the results. This team's habits may differ from those of other learners."},
    {id:"mr3",question:"What most strengthens an explanation?",options:["A claim linked to relevant evidence and reasoning","Repeating the claim loudly","Using a longer word","Ignoring other explanations"],correctAnswer:0,explanation:"Reasoning explains how the evidence supports a claim. Considering alternatives can strengthen the judgement."}]},
];
