/** @jest-environment node */
import { unzipSync, strFromU8 } from "fflate";
import { buildPowerPoint, docxBlob, pdfBlob, pdfDefinition, documentBlocks } from "./resource-export";
const title="Evidence & inquiry";
const markdown="# Evidence & inquiry\n\n## Try this\nCompare café observations with Δ temperature = 2 °C.\n\n- Explain your reasoning\n\n| Criterion | Evidence |\n| --- | --- |\n| Explanation | A clear example |\n\nhttps://IBgenie.com";
const deck={slides:[{id:"s1",layout:"explain" as const,title,bullets:["Compare observations.","Explain the change: 2 °C."],prompt:"What would change your mind?",notes:"Answer: evaluate reliability before making a claim. Source: https://IBgenie.com"}]};
it("exports a real editable PowerPoint with notes and only brand links",async()=>{const ppt=await buildPowerPoint(title,deck);const buffer=await ppt.write({outputType:"uint8array",compression:true}) as Uint8Array;const zip=unzipSync(buffer),xml=strFromU8(zip["ppt/slides/slide1.xml"]);expect(xml).toContain("<a:t>Evidence &amp; inquiry</a:t>");expect(xml).toContain("Compare observations.");expect(strFromU8(zip["ppt/notesSlides/notesSlide1.xml"])).toContain("evaluate reliability");const text=Object.values(zip).map(bytes=>strFromU8(bytes)).join("");expect(text).toContain("https://IBgenie.com");expect(text).not.toContain("vercel.app");if(process.env.IBGENIE_EXPORT_QA_DIR){const fs=await import("node:fs/promises");await fs.mkdir(process.env.IBGENIE_EXPORT_QA_DIR,{recursive:true});await fs.writeFile(process.env.IBGENIE_EXPORT_QA_DIR+"/classroom.pptx",buffer);}});
it("exports a native Word document with editable tables and branded footer",async()=>{const blob=await docxBlob(title,markdown),buffer=new Uint8Array(await blob.arrayBuffer()),zip=unzipSync(buffer);const xml=strFromU8(zip["word/document.xml"]);expect(xml).toContain("<w:tbl>");expect(xml).toContain("café");const text=Object.values(zip).map(bytes=>strFromU8(bytes)).join("");expect(text).toContain("IBgenie.com");expect(text).not.toContain("vercel.app");if(process.env.IBGENIE_EXPORT_QA_DIR){const fs=await import("node:fs/promises");await fs.writeFile(process.env.IBGENIE_EXPORT_QA_DIR+"/resource.docx",buffer);}});
it("creates a PDF with an embedded font and a fixed branded link rather than the page location",async()=>{const blob=await pdfBlob(title,markdown),buffer=Buffer.from(await blob.arrayBuffer());expect(buffer.subarray(0,5).toString()).toBe("%PDF-");expect(buffer.toString("latin1")).toContain("/FontFile2");expect(buffer.toString("latin1")).toContain("https://IBgenie.com");expect(buffer.toString("latin1")).not.toContain("vercel.app");expect(pdfDefinition(title,markdown).info?.creator).toBe("IBgenie.com");if(process.env.IBGENIE_EXPORT_QA_DIR){const fs=await import("node:fs/promises");await fs.writeFile(process.env.IBGENIE_EXPORT_QA_DIR+"/resource.pdf",buffer);}});
it("preserves Markdown table cells as a native table",()=>{const table=documentBlocks(markdown).find(b=>b.kind==="table");expect(table).toEqual({kind:"table",rows:[["Criterion","Evidence"],["Explanation","A clear example"]]});});
