"use client";
import {useCallback,useEffect,useState} from "react";import {KeyRound,LoaderCircle,PlugZap,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";import {Input} from "@/components/ui/input";import {ErrorNote} from "./shared";
type Status={configured:boolean;authenticated:boolean;text:boolean;voice:boolean};
export function useAIStatus(){const[status,setStatus]=useState<Status>();const[statusError,setError]=useState("");const refresh=useCallback(async()=>{try{const r=await fetch("/api/access",{cache:"no-store"});if(!r.ok)throw new Error();setStatus(await r.json());setError("");}catch{setError("Could not check the AI connection.");}},[]);useEffect(()=>{void refresh();},[refresh]);return{status,statusError,refresh};}
export function AccessGate({status,statusError,refresh,capability="text"}:ReturnType<typeof useAIStatus>&{capability?:"text"|"voice"}){const[code,setCode]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const unlock=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setCode("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}};
if(statusError)return <ErrorNote>{statusError} <button className="text-button" onClick={refresh}>Retry</button></ErrorNote>;
if(!status)return <div className="info-note"><LoaderCircle className="animate-spin" size={16}/>Checking AI connection…</div>;
if(!status[capability])return <div className="connection-note"><PlugZap size={23}/><div><strong>{capability==="voice"?"Voice coaching":"AI tools"} is not connected yet.</strong><p>The workspace owner needs to enable this connection. You can create resources, practice and plan your work now.</p></div></div>;
if(status.authenticated)return <div className="access-ready"><ShieldCheck size={16}/>AI connection enabled for this session</div>;
return <div className="access-form"><KeyRound size={22}/><div><strong>Have a workspace access code?</strong><p>Use the code your teacher or workspace owner gave you.</p><form onSubmit={unlock}><Input type="password" autoComplete="current-password" aria-label="AI access code" value={code} maxLength={256} onChange={e=>setCode(e.target.value)} required/><Button type="submit" disabled={busy}>{busy?"Connecting…":"Unlock AI tools"}</Button></form>{error&&<ErrorNote>{error}</ErrorNote>}</div></div>;
}
