import {createHash,createHmac,randomBytes,timingSafeEqual} from "node:crypto";
import {NextResponse} from "next/server";
import {ZodError} from "zod";
export class ApiError extends Error{constructor(public status:number,message:string){super(message);}}
const COOKIE="ibgenie_access";const buckets=new Map<string,{count:number;expires:number}>();
export function accessConfigured(){return(process.env.AI_ACCESS_CODE?.length??0)>=12&&(process.env.SESSION_SECRET?.length??0)>=32&&(process.env.NODE_ENV!=="production"||!!(process.env.APP_ORIGIN&&process.env.UPSTASH_REDIS_REST_URL&&process.env.UPSTASH_REDIS_REST_TOKEN));}
export function sameOrigin(r:Request){if(!r.headers.get("origin")||r.headers.get("origin")!==(process.env.APP_ORIGIN||new URL(r.url).origin))throw new ApiError(403,"Open this action from your IBGenie workspace.");}
export function secureEqual(a:string,b:string){return timingSafeEqual(createHash("sha256").update(a).digest(),createHash("sha256").update(b).digest());}
function sign(v:string){return createHmac("sha256",process.env.SESSION_SECRET||"").update(v).digest("base64url");}
export function sessionIdentity(r:Request):string|null{if(!accessConfigured())return null;const token=r.headers.get("cookie")?.split(";").map(v=>v.trim()).find(v=>v.startsWith(COOKIE+"="))?.slice(COOKIE.length+1);if(!token||token.length>400)return null;const[id,expires,signature,extra]=token.split(".");if(extra||!id||!expires||!signature||!/^[a-f0-9]{32}$/.test(id)||!/^\d+$/.test(expires)||Number(expires)<Date.now())return null;return secureEqual(signature,sign(id+"."+expires))?id:null;}
export function createAccessCookie(r:NextResponse){const payload=randomBytes(16).toString("hex")+"."+(Date.now()+8*3600000);r.cookies.set(COOKIE,payload+"."+sign(payload),{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:8*3600});}
export function clearAccessCookie(r:NextResponse){r.cookies.set(COOKIE,"",{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"strict",path:"/",maxAge:0});}
export async function rateLimit(key:string,limit:number,seconds:number){const url=process.env.UPSTASH_REDIS_REST_URL,token=process.env.UPSTASH_REDIS_REST_TOKEN;
if(url&&token){if(!url.startsWith("https://"))throw new ApiError(503,"AI access needs configuration.");try{const r=await fetch(url,{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(["EVAL","local n=redis.call('INCR',KEYS[1]); if n==1 then redis.call('EXPIRE',KEYS[1],ARGV[1]) end; return n","1","ibgenie:rate:"+key,String(seconds)]),signal:AbortSignal.timeout(5000),cache:"no-store"});const d=await r.json();if(!r.ok||typeof d.result!=="number")throw new Error();if(d.result>limit)throw new ApiError(429,"This workspace has reached its AI usage limit. Try again later.");}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(503,"AI access is temporarily unavailable.");}return;}
if(process.env.NODE_ENV==="production")throw new ApiError(503,"AI access needs configuration.");const now=Date.now();for(const[k,v]of buckets)if(v.expires<now)buckets.delete(k);const b=buckets.get(key)||{count:0,expires:now+seconds*1000};b.count++;buckets.set(key,b);if(b.count>limit)throw new ApiError(429,"Too many requests. Try again later.");}
export async function requireAI(r:Request,capability:"text"|"voice"="text"){sameOrigin(r);if(!accessConfigured())throw new ApiError(503,"AI tools are not connected yet. You can still create resources and study without AI.");const id=sessionIdentity(r);if(!id)throw new ApiError(401,"Enter your workspace access code to use AI.");if(!(capability==="voice"?process.env.OPENAI_API_KEY:process.env.GEMINI_API_KEY))throw new ApiError(503,"This AI service is not connected yet.");await rateLimit("user:"+id+":"+capability,capability==="voice"?3:15,60);await rateLimit("workspace:"+capability,capability==="voice"?30:300,86400);return id;}
export async function readLimited(r:Request,maxBytes=100000){const length=Number(r.headers.get("content-length"));if(Number.isFinite(length)&&length>maxBytes)throw new ApiError(413,"Use a shorter selection.");if(!r.body)throw new ApiError(400,"Add content to your request.");const reader=r.body.getReader(),chunks:Uint8Array[]=[];let size=0;try{while(true){const v=await reader.read();if(v.done)break;size+=v.value.byteLength;if(size>maxBytes){await reader.cancel();throw new ApiError(413,"Use a shorter selection.");}chunks.push(v.value);}}finally{reader.releaseLock();}return Buffer.concat(chunks);}
export async function readJson(r:Request){try{return JSON.parse((await readLimited(r)).toString("utf8"));}catch(e){if(e instanceof ApiError)throw e;throw new ApiError(400,"The request was not valid JSON.");}}
export function apiFailure(e:unknown){const status=e instanceof ApiError?e.status:e instanceof ZodError||e instanceof SyntaxError?400:502;return NextResponse.json({error:e instanceof ApiError?e.message:status===400?"Check the fields and try again.":"The AI service could not complete this request. Your work is still here."},{status,headers:{"Cache-Control":"no-store",...(status===429?{"Retry-After":"60"}:{})}});}
