import "server-only";
import {z} from "zod";import {appOrigin,envInt} from "./config";import {redis} from "./redis";import {ApiError} from "./errors";import {signToken,verifyToken,randomId} from "./tokens";
const callIdSchema=z.string().regex(/^[a-zA-Z0-9_-]{6,200}$/);
const stopSchema=z.object({purpose:z.literal("voice-stop"),callId:callIdSchema,jti:z.string(),exp:z.number().int()}).strict();
const timeoutSchema=z.object({purpose:z.literal("voice-timeout"),callId:callIdSchema,jti:z.string(),notBefore:z.number().int(),exp:z.number().int()}).strict();
function key(id:string){return"ibgenie:voice:"+id;}
export async function hangupCall(id:string){callIdSchema.parse(id);const r=await fetch("https://api.openai.com/v1/realtime/calls/"+encodeURIComponent(id)+"/hangup",{method:"POST",headers:{Authorization:"Bearer "+process.env.OPENAI_API_KEY},cache:"no-store",signal:AbortSignal.timeout(8000)});if(!r.ok&&![404,409,410].includes(r.status))throw new ApiError(502,"The voice service could not confirm the end of this call.");}
export async function scheduleVoiceEnd(id:string,identity:string){callIdSchema.parse(id);if(!process.env.QSTASH_TOKEN||!appOrigin())throw new ApiError(503,"Live voice needs its session timer connected.");const seconds=envInt("VOICE_SESSION_MINUTES",10,1,30)*60,now=Math.floor(Date.now()/1000),jti=randomId(),record={identity,jti,deadline:now+seconds};await redis(["SET",key(id),JSON.stringify(record),"EX",172800]);const token=signToken({purpose:"voice-timeout",callId:id,jti,notBefore:record.deadline,exp:now+172800},process.env.SESSION_SECRET||"");const r=await fetch("https://qstash.upstash.io/v2/publish/"+appOrigin()+"/api/realtime/timeout",{method:"POST",headers:{Authorization:"Bearer "+process.env.QSTASH_TOKEN,"Content-Type":"application/json","Upstash-Delay":seconds+"s","Upstash-Retries":"5","Upstash-Retry-Delay":"1000 * (1 + retried)","Upstash-Redact-Fields":"body"},body:JSON.stringify({token}),cache:"no-store",signal:AbortSignal.timeout(8000)});if(!r.ok)throw new ApiError(503,"The voice session timer could not start. Please try again.");return{stopToken:signToken({purpose:"voice-stop",callId:id,jti,exp:now+seconds+300},process.env.SESSION_SECRET||""),maxSeconds:seconds};}
export async function stopVoice(token:string,scheduled=false){let data;try{const payload=verifyToken(token,process.env.SESSION_SECRET||"");data=scheduled?timeoutSchema.parse(payload):stopSchema.parse(payload);}catch{throw new ApiError(401,"This voice control could not be verified.");}const now=Math.floor(Date.now()/1000);if(data.exp<=now)throw new ApiError(401,"This voice control expired.");if(scheduled&&"notBefore"in data&&data.notBefore>now+2)throw new ApiError(425,"The voice session timer is not due yet.");const raw=await redis<string|null>(["GET",key(data.callId)]);if(!raw)return;const record=JSON.parse(raw);if(record.jti!==data.jti)throw new ApiError(403,"This voice control does not match the session.");await hangupCall(data.callId);await redis(["DEL",key(data.callId)]);}
